// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InspireTest extends TestBase {

  @Test
  public void inspire() {
    app.navigation.openItemsPage();
    Random random = new Random();
    Item item = new Item("testcase last " + random.nextInt(5), "cyan", "1000");
    app.item.createNewItem(item);
    Item newItem = app.item.getCreatedItem();
    Assert.assertEquals(item.name, newItem.name);
  }
  @Test
  public void work() {
    AccountData user = new AccountData("test","Iamtesting!1" );
    app.navigation.openHomePage();
    app.auth.login(user);
    app.navigation.openWorksPage();
    Work work = new Work("my latest work", "okay");
    app.work.createNewWork(work);
    Work newWork = app.work.getCreatedWork();
    Assert.assertEquals(work.getTitle(),newWork.getTitle());
  }
}
